# Generated by Django 3.1.7 on 2021-04-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_resumejob_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumejob',
            name='company',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='resumejob',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
    ]
