# Generated by Django 3.1.7 on 2021-04-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20210401_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeeducation',
            name='name',
            field=models.CharField(max_length=350),
        ),
    ]
